const READING_DOMAINS: Set<string> = new Set([
  // ── English Newspapers ──
  "nytimes.com",
  "washingtonpost.com",
  "theguardian.com",
  "telegraph.co.uk",
  "thetimes.co.uk",
  "wsj.com",
  "ft.com",
  "latimes.com",
  "chicagotribune.com",
  "bostonglobe.com",
  "usatoday.com",
  "nypost.com",
  "sfchronicle.com",
  "seattletimes.com",
  "denverpost.com",
  "dallasnews.com",
  "houstonchronicle.com",
  "ajc.com",
  "miamiherald.com",
  "tampabay.com",
  "oregonlive.com",
  "nj.com",
  "philly.com",
  "baltimoresun.com",
  "stltoday.com",
  "startribune.com",
  "jsonline.com",
  "indystar.com",
  "freep.com",
  "detroitnews.com",
  "independent.co.uk",
  "dailymail.co.uk",
  "thesun.co.uk",
  "mirror.co.uk",
  "express.co.uk",
  "standard.co.uk",
  "metro.co.uk",
  "theaustralian.com.au",
  "smh.com.au",
  "theage.com.au",
  "afr.com",
  "thestar.com",
  "theglobeandmail.com",
  "nationalpost.com",
  "thehindu.com",
  "indiatimes.com",
  "hindustantimes.com",
  "indianexpress.com",
  "thenational.ae",
  "straitstimes.com",
  "bangkokpost.com",

  // ── Spanish Newspapers ──
  "elpais.com",
  "elmundo.es",
  "lavanguardia.com",
  "abc.es",
  "elconfidencial.com",
  "eldiario.es",
  "20minutos.es",
  "lasexta.com",
  "clarin.com",
  "lanacion.com.ar",
  "pagina12.com.ar",
  "infobae.com",
  "eluniversal.com.mx",
  "jornada.com.mx",
  "reforma.com",
  "milenio.com",
  "excelsior.com.mx",
  "eleconomista.com.mx",
  "elpais.com.co",
  "eltiempo.com",
  "elespectador.com",
  "emol.com",
  "latercera.com",
  "elmercurio.com",
  "elcomercio.pe",
  "larepublica.pe",
  "eluniversal.com.ve",
  "elnuevoherald.com",

  // ── Japanese Newspapers ──
  "asahi.com",
  "mainichi.jp",
  "yomiuri.co.jp",
  "nikkei.com",
  "sankei.com",
  "tokyo-np.co.jp",
  "chunichi.co.jp",
  "nishinippon.co.jp",
  "kahoku.co.jp",
  "chugoku-np.co.jp",
  "kyoto-np.co.jp",
  "kobe-np.co.jp",
  "47news.jp",
  "jiji.com",
  "japantimes.co.jp",
  "japantoday.com",

  // ── Chinese News Sites ──
  "scmp.com",
  "caixin.com",
  "thepaper.cn",
  "chinadaily.com.cn",
  "globaltimes.cn",
  "xinhuanet.com",
  "people.com.cn",
  "163.com",
  "sina.com.cn",
  "sohu.com",
  "qq.com",
  "ifeng.com",
  "eastday.com",
  "huanqiu.com",
  "takungpao.com",
  "wenweipo.com",
  "mingpao.com",
  "hk01.com",
  "ettoday.net",
  "udn.com",
  "ltn.com.tw",
  "chinatimes.com",
  "cna.com.tw",

  // ── French Newspapers ──
  "lemonde.fr",
  "lefigaro.fr",
  "liberation.fr",
  "leparisien.fr",
  "lepoint.fr",
  "lexpress.fr",
  "nouvelobs.com",
  "humanite.fr",
  "lacroix.com",
  "lesechos.fr",
  "latribune.fr",
  "20minutes.fr",
  "ouest-france.fr",
  "sudouest.fr",
  "lavoixdunord.fr",
  "mediapart.fr",
  "courrierinternational.com",
  "letemps.ch",
  "tdg.ch",
  "24heures.ch",
  "lapresse.ca",
  "ledevoir.com",
  "radio-canada.ca",

  // ── German Newspapers ──
  "faz.net",
  "sueddeutsche.de",
  "zeit.de",
  "spiegel.de",
  "welt.de",
  "bild.de",
  "focus.de",
  "stern.de",
  "handelsblatt.com",
  "wiwo.de",
  "tagesspiegel.de",
  "tagesschau.de",
  "taz.de",
  "fr.de",
  "berliner-zeitung.de",
  "n-tv.de",
  "t-online.de",
  "heise.de",
  "derstandard.at",
  "kurier.at",
  "kleinezeitung.at",
  "nzz.ch",
  "blick.ch",
  "tagesanzeiger.ch",

  // ── Portuguese Newspapers ──
  "folha.uol.com.br",
  "oglobo.globo.com",
  "estadao.com.br",
  "uol.com.br",
  "globo.com",
  "terra.com.br",
  "ig.com.br",
  "abril.com.br",
  "exame.com",
  "publico.pt",
  "jn.pt",
  "dn.pt",
  "observador.pt",
  "expresso.pt",
  "cmjornal.pt",
  "record.pt",
  "sapo.pt",
  "rtp.pt",

  // ── Korean Newspapers ──
  "chosun.com",
  "joongang.co.kr",
  "hani.co.kr",
  "donga.com",
  "khan.co.kr",
  "mk.co.kr",
  "hankyung.com",
  "mt.co.kr",
  "sedaily.com",
  "hankookilbo.com",
  "segye.com",
  "seoul.co.kr",
  "newsis.com",
  "yonhapnews.co.kr",
  "yna.co.kr",
  "nocutnews.co.kr",

  // ── Italian Newspapers ──
  "repubblica.it",
  "corriere.it",
  "lastampa.it",
  "ilsole24ore.com",
  "ilmessaggero.it",
  "ilgiornale.it",
  "ansa.it",
  "adnkronos.com",
  "ilfattoquotidiano.it",
  "ilpost.it",
  "fanpage.it",
  "leggo.it",
  "quotidiano.net",
  "ilgazzettino.it",
  "ilrestodelcarlino.it",

  // ── Arabic News Sites ──
  "aljazeera.net",
  "alarabiya.net",
  "aawsat.com",
  "alhurra.com",
  "alaraby.co.uk",
  "skynewsarabia.com",
  "alhayat.com",
  "elaph.com",
  "youm7.com",
  "almasryalyoum.com",
  "ahram.org.eg",
  "alghad.com",
  "addustour.com",
  "sabq.org",
  "okaz.com.sa",

  // ── TV/Broadcast News ──
  "bbc.com",
  "bbc.co.uk",
  "cnn.com",
  "nbcnews.com",
  "cbsnews.com",
  "abcnews.go.com",
  "foxnews.com",
  "pbs.org",
  "msnbc.com",
  "npr.org",
  "aljazeera.com",
  "nhk.or.jp",
  "cctv.com",
  "france24.com",
  "dw.com",
  "rai.it",
  "kbs.co.kr",
  "mbc.co.kr",
  "sbs.co.kr",
  "rte.ie",
  "cbc.ca",
  "ctv.ca",
  "sky.com",
  "itv.com",
  "channel4.com",
  "euronews.com",

  // ── Digital-First News & Aggregators ──
  "huffpost.com",
  "buzzfeed.com",
  "vox.com",
  "axios.com",
  "thedailybeast.com",
  "politico.com",
  "thehill.com",
  "slate.com",
  "salon.com",
  "propublica.org",
  "theintercept.com",
  "news.google.com",
  "news.yahoo.com",
  "news.ycombinator.com",
  "lobste.rs",
  "digg.com",

  // ── Wire Services & Agencies ──
  "reuters.com",
  "apnews.com",
  "afp.com",
  "efe.com",
  "kyodonews.net",
  "dpa.com",

  // ── Magazines & Long-form ──
  "theatlantic.com",
  "newyorker.com",
  "economist.com",
  "time.com",
  "newsweek.com",
  "vanityfair.com",
  "gq.com",
  "wired.com",
  "foreignaffairs.com",
  "foreignpolicy.com",
  "nationalgeographic.com",
  "smithsonianmag.com",
  "harpers.org",
  "newrepublic.com",
  "thenation.com",
  "prospect.org",
  "prospect.co.uk",
  "spectator.co.uk",
  "newstatesman.com",
  "lrb.co.uk",
  "nybooks.com",
  "esquire.com",
  "rollingstone.com",
  "fastcompany.com",
  "inc.com",
  "forbes.com",
  "fortune.com",
  "bloomberg.com",
  "businessinsider.com",
  "entrepreneur.com",
  "hbr.org",

  // ── Tech News ──
  "techcrunch.com",
  "arstechnica.com",
  "theverge.com",
  "engadget.com",
  "cnet.com",
  "zdnet.com",
  "gizmodo.com",
  "theregister.com",
  "tomshardware.com",
  "pcmag.com",
  "techradar.com",
  "tomsguide.com",
  "macrumors.com",
  "9to5mac.com",
  "appleinsider.com",
  "androidcentral.com",
  "androidpolice.com",
  "xda-developers.com",
  "slashdot.org",
  "hackernoon.com",
  "infoq.com",
  "thenextweb.com",
  "venturebeat.com",

  // ── Blog Platforms & Blogging Sites ──
  "medium.com",
  "substack.com",
  "dev.to",
  "hashnode.com",
  "wordpress.com",
  "blogger.com",
  "blogspot.com",
  "tumblr.com",
  "ghost.org",
  "write.as",
  "bearblog.dev",
  "themarginalian.org",
  "waitbutwhy.com",
  "fs.blog",
  "stratechery.com",
  "daringfireball.net",
  "kottke.org",
  "metafilter.com",
  "marginalrevolution.com",
  "lesswrong.com",
  "paulgraham.com",
  "codinghorror.com",
  "calnewport.com",
  "markmanson.net",
  "zenhabits.net",
  "jamesclear.com",
  "theschooloflife.com",

  // ── Science & Research ──
  "arxiv.org",
  "pubmed.ncbi.nlm.nih.gov",
  "nature.com",
  "science.org",
  "scientificamerican.com",
  "technologyreview.com",
  "quantamagazine.org",
  "nautil.us",
  "plos.org",
  "biorxiv.org",
  "medrxiv.org",
  "ssrn.com",
  "researchgate.net",
  "scholar.google.com",
  "jstor.org",
  "academia.edu",
  "sciencedirect.com",
  "springer.com",
  "wiley.com",
  "cell.com",
  "thelancet.com",
  "bmj.com",
  "nejm.org",
  "pnas.org",
  "acs.org",
  "aps.org",
  "ieee.org",
  "acm.org",

  // ── Sports ──
  "espn.com",
  "theathletic.com",
  "bleacherreport.com",
  "si.com",
  "sbnation.com",
  "cbssports.com",
  "foxsports.com",
  "nbcsports.com",
  "skysports.com",
  "lequipe.fr",
  "marca.com",
  "as.com",
  "mundodeportivo.com",
  "sport.es",
  "gazzetta.it",
  "corrieredellosport.it",
  "tuttosport.com",
  "kicker.de",
  "goal.com",
  "transfermarkt.com",

  // ── Book & Ebook Sites ──
  "gutenberg.org",
  "openlibrary.org",
  "archive.org",
  "books.google.com",
  "read.amazon.com",
  "librivox.org",
  "standardebooks.org",
  "feedbooks.com",
  "manybooks.net",
  "smashwords.com",
  "bookbub.com",
  "scribd.com",

  // ── Web Novel Platforms ──
  "wattpad.com",
  "royalroad.com",
  "webnovel.com",
  "tapas.io",
  "kakuyomu.jp",
  "syosetu.com",
  "pixiv.net",
  "novelupdates.com",
  "munpia.com",
  "series.naver.com",
  "joara.com",
  "novelpia.com",
  "qidian.com",
  "zongheng.com",
  "scribblehub.com",
  "penana.com",
  "inkitt.com",

  // ── Fan Fiction ──
  "archiveofourown.org",
  "fanfiction.net",
  "fictionpress.com",
  "quotev.com",
  "asianfanfics.com",

  // ── Curation & Read-Later ──
  "longform.org",
  "longreads.com",
  "instapaper.com",
  "getpocket.com",
  "thebrowser.com",
  "aldaily.com",
  "realclearpolitics.com",
  "delanceyplace.com",

  // ── Book Discovery & Literary Reviews ──
  "goodreads.com",
  "thestorygraph.com",
  "librarything.com",
  "lithub.com",
  "electricliterature.com",
  "theparisreview.org",
  "granta.com",
  "tinhouse.com",
  "themillions.com",
  "bookpage.com",
  "lareviewofbooks.org",
  "publicbooks.org",

  // ── Opinion, Commentary & Essays ──
  "theconversation.com",
  "quillette.com",
  "aeon.co",
  "psyche.co",
  "project-syndicate.org",
  "opendemocracy.net",
  "persuasion.community",
  "thebulwark.com",
  "currentaffairs.org",
  "jacobin.com",
  "reason.com",
  "nationalreview.com",
  "tabletmag.com",
  "commonwealmagazine.org",

  // ── Reference ──
  "wikipedia.org",
  "britannica.com",
  "encyclopedia.com",

  // ── Additional International ──
  "thediplomat.com",
  "chinafile.com",
  "sixthtone.com",
  "koreaherald.com",
  "koreatimes.co.kr",
  "thejakartapost.com",
  "rappler.com",
  "inquirer.net",
  "channelnewsasia.com",
  "vnexpress.net",
  "dawn.com",
  "haaretz.com",
  "timesofisrael.com",
  "jpost.com",
  "dailysabah.com",
  "trtworld.com",
]);

function matchesDomainSet(
  url: string,
  domainSet: Set<string> | ReadonlySet<string>,
): boolean {
  let domain = new URL(url).hostname;
  while (domain.includes(".")) {
    if (domainSet.has(domain)) return true;
    domain = domain.slice(domain.indexOf(".") + 1);
  }
  return false;
}

export function isReadingDomain(
  url: string | null,
  customDomains?: string[],
): boolean {
  if (!url) return false;
  try {
    if (matchesDomainSet(url, READING_DOMAINS)) return true;
    if (customDomains && customDomains.length > 0) {
      return matchesDomainSet(url, new Set(customDomains));
    }
    return false;
  } catch {
    return false;
  }
}
